name: publish
on: [push]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:
    - uses: actions/checkout@v2

    - name: GitHub Container Registry Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Image Build
      run: |
        if [[ "$GITHUB_REF_NAME" == "master" ]]; then export TAG_NAME="latest"; else export TAG_NAME="$GITHUB_REF_NAME"; fi
        echo "Building jpf91/thesis-latex:$TAG_NAME"
        docker build . --tag ghcr.io/jpf91/thesis-latex:$TAG_NAME
        docker push ghcr.io/jpf91/thesis-latex:$TAG_NAME
